### PR TITLE
Tweaks & suggestions

### PR DESCRIPTION
**Pull request by purcell**
No need to merge this, of course, but I thought it would be a convenient way to break down some possible fixes/improvements.

I'll probably tinker a little more.

### CODE REVIEW

**Comment by vapniks** [comment]
If you can come up with something with runtime faster than O(n!) then let me know. 
It would be nice to incorporate it into my haskell playlist creator: https://github.com/vapniks/playlist-creator

**Comment by purcell** [comment]
@krisajenkins Yep, see the corresponding section of [my bin-packing code](https://github.com/purcell/spotify-pack/blob/master/SpotifyPack.hs#L46-L71), in which I started off generically, from first principles. I tried yesterday to smoothly refactor the knapsack code into that sort of shape, eliminating `Item` along the way, but couldn't easily "show my working"... so I gave up.

**Comment by purcell** [comment]
@krisajenkins Which part of the computation needs to be memoized?

**Comment by purcell** [comment]
> I just did a couple of force-pushes

Wash your mouth out!

**Comment by purcell** [comment]
P.S. I can highly recommend installing the `stylish` tool/package globally, and setting `haskell-stylish-on-save` to `t`: this has the effect of sorting/reformatting your `import`s when the buffer is saved.

**Comment by purcell** [comment]
I hope to cover some of the basic haskell-mode setup and workflow stuff in a screencast.

**Comment by purcell** [comment]
Re. the memoization, are you sure the recursive functions will end up getting called repeatedly with the same exact args? I'm not seeing how that can happen when the items-to-be-packed are held in a list. (Disclaimer: only 1 coffee has passed my lips today.)

**Comment by purcell** [comment]
Ah, right, so just in the `uks` case, in which the item set is always the same. But whether memoisation is a win will depend heavily on the distribution of weights. In the spotify case, for example, the track durations would rarely be identical.

**Comment by vapniks** [comment]
I've made a parallelized version. Doesn't seem to give much speedup though: https://github.com/vapniks/knapsack-haskell
Might be able to get better results using the par monad.

**Pull request closed without merging**
